<script>

export const SidebarIcon = Object.freeze({
    DASHBOARD: "bi bi-grid",
    SETTING: "bi bi-gear-fill",
    CONFIGURATION: "bi bi-gear",
    BRANCH: "bi bi-diagram-3",
    DEPARTMENT: "bi bi-node-plus",
    DESIGNATION: "bi bi-mortarboard-fill",
    DOCUMENT: "bi bi-escape",
    SHIFT: "bi bi-alarm-fill",
    HOLIDAY: "bi bi-balloon-heart",
    FISCAL_YEAR: "bi bi-calendar2-minus",
    LEAVE_TYPE: "bi bi-calendar2",
    LEAVE_SETTING: "bi bi-calendar2-event-fill",
    TASK: "bi bi-pc-display",
    TASK_HOME: "bi bi-person-workspace",
    HELP_DESK: "bi bi-pc-horizontal",
    REQUESTS: "bi bi-calendar2-check",
    LEAVE_REQUEST: "bi bi-calendar2-range",
    EVENT: "bi bi-calendar2-range",
    COMPENSATORY: "bi bi-calendar2-event",
    HANDOVER: "bi bi-send-plus-fill",
    ATTENDANCE_HANDLER: "bi bi-briefcase-fill",
    HR_HANDLER: "bi bi-briefcase-fill",
    HRM: "bi bi-briefcase-fill",
    STAFFS: "bi bi-person-fill",
    REPORT: "bi bi-card-text",
    ATTENDANCE: "bi bi-calendar2-check",
    DAILY_TASK: "bi bi-bar-chart-steps",
    CALENDAR: "bi bi-calendar3",
    SUGGESTION_FOR: "bi bi-tags",
    SUGGESTION: "bi bi-chat-left-quote",
    NOTICE: "bi bi-journal-text",
    SURVEY: "bi bi-chat-right-text",
    ORG_CHART: 'bi bi-diagram-3-fill',
    ADJUSTMENT_FOR: "bi bi-tags",
    ADJUSTMENT: "bi bi-chat-left-quote",
    OVERTIME_FOR: "bi bi-tags",
    OVERTIME: "bi bi-chat-left-quote",
    EXIT_INTERVIEW: "bi bi-chat-left-quote",
    BOOKING_PLACE: "bi bi-house",
    BOOKING_HALL: "bi bi-house-door",
    BOOKING_PURPOSE: "bi bi-house-fill",
    BOOKING: "bi bi-calendar-check",
    BOOKINGTIME: "bi bi-stopwatch",
    DIVISION: "bi bi-arrow-left-right",
    REVENUE: "bi bi-bookshelf",
    EDUCATION: "bi bi-book",
    FACULTY: "bi bi-journal",
    SUBORDINATE: "bi bi-people",
    LETTER: "bi bi-chat-left-text",
    TRAINING: "bi bi-easel",
    TRAINER: "bi bi-person-badge-fill",
    TRAINING_PROGRAM: "bi bi-book",
    OVERVIEW: "bi bi-cast",
    TRAVEL_ASSIGNMENT_TYPE: "bi bi-bookmark-plus",
    TRAVEL_ASSIGNMENT_CATEGORY: "bi bi-tags",
    TRAVEL: "bi bi-airplane",
    TRAVEL_MAIN: "bi bi-fuel-pump-fill",
    TRAVEL_PLANNER: "bi bi-calendar-week-fill",
    TRAVEL_REPORT: "bi bi-cash-stack",
    OUTSOURCE: "bi bi-box-seam",
    ONBOARDING: "bi bi-person-square",
    OFFBOARDING: "bi bi-box-arrow-up-right",
    OFFBOARDING_ITEM: "bi bi-box-seam",
    NEWSFEED: "bi bi-rss-fill",
    JOB: "bi bi-briefcase-fill",
    JOBPOST: "bi bi-briefcase-fill",
    JOBLEVEL: "bi bi-diagram-2",
    JOBLOCATION: "bi bi-geo",
    JOBPROCESS: "bi bi-arrow-left-right",
    
});

</script>
