<?php

return [

    'templates' => [
        [
            'title' => 'Template One',
            'description' => '<p style="text-align:right"><span style="font-family:Georgia,serif"><span style="font-size:12px">Ref. No: - 5166/App/RPPL/2019</span></span></p><p><span style="font-family:Georgia,serif"><span style="font-size:12px">Date: *today*</span></span></p><p>&nbsp;</p><p style="text-align:center"><span style="font-family:Georgia,serif"><span style="font-size:14px"><strong>*letter-type*</strong></span></span></p><p><span style="font-family:Georgia,serif">To,</span></p><p><span style="font-family:Georgia,serif">*title* *employee-name*</span></p><p><span style="font-family:Georgia,serif">Kathmandu, Nepal</span></p><p>&nbsp;</p><p><span style="font-family:Georgia,serif">Dear *title* *last-name*</span></p><p style="text-align:justify"><span style="font-family:Georgia,serif"><strong>Lorem Ipsum</strong>&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </span></p><p style="text-align:justify"><span style="font-family:Georgia,serif">It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.&nbsp;It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using &#39;Content here, content here&#39;, making it look like readable English.</span></p><p style="text-align:justify"><span style="font-family:Georgia,serif">The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.</span></p><p>&nbsp;</p><p><span style="font-family:Georgia,serif">Sincerely</span></p><p><span style="font-family:Georgia,serif">*signature**stamp*</span></p><p><span style="font-family:Georgia,serif">*letter-handler*</span></p><p><span style="font-family:Georgia,serif">*letter-handler-designation*</span></p>'
        ],
        [
            'title' => 'Template Two',
            'description' => '<p style="text-align:right"><span style="font-family:Georgia,serif"><span style="font-size:12px">Ref. No: - 5166/App/RPPL/2019</span></span></p><p><span style="font-family:Georgia,serif"><span style="font-size:12px">Date: *today*</span></span></p><p>&nbsp;</p><p style="text-align:center"><span style="font-family:Georgia,serif"><span style="font-size:14px"><strong>*letter-type*</strong></span></span></p><p><span style="font-family:Georgia,serif">To,</span></p><p><span style="font-family:Georgia,serif">*title* *employee-name*</span></p><p><span style="font-family:Georgia,serif">Kathmandu, Nepal</span></p><p>&nbsp;</p><p><span style="font-family:Georgia,serif">Dear *title* *last-name*</span></p><p style="text-align:justify"><span style="font-family:Georgia,serif"><strong>Lorem Ipsum</strong>&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </span></p><p style="text-align:justify"><span style="font-family:Georgia,serif">It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.&nbsp;It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using &#39;Content here, content here&#39;, making it look like readable English.</span></p><p style="text-align:justify"><span style="font-family:Georgia,serif">The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.</span></p><p>&nbsp;</p><p><span style="font-family:Georgia,serif">Sincerely</span></p><p><span style="font-family:Georgia,serif">*signature**stamp*</span></p><div style="float:left;"><p><span style="font-family:Georgia,serif">*letter-handler*</span></p><p><span style="font-family:Georgia,serif">*letter-handler-designation*</span></p></div><div style="float:right;"><p><span style="font-family:Georgia,serif">*employee-name*</span></p><p><span style="font-family:Georgia,serif">*today*</span></p></div>'
        ],
        [
            'title' => 'Template Three',
            'description' => '<p style="text-align:right"><span style="font-family:Georgia,serif"><span style="font-size:12px">Date: *today*</span></span></p><p><span style="font-family:Georgia,serif">Dear *employee-name*</span></p><p style="text-align:center"><span style="font-family:Georgia,serif"><span style="font-size:14px"><strong>*letter-type*</strong></span></span></p><p style="text-align:justify"><span style="font-family:Georgia,serif"><strong>Lorem Ipsum</strong>&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </span></p><p style="text-align:justify"><span style="font-family:Georgia,serif">It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.&nbsp;It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</span></p><p style="text-align:justify"><span style="font-family:Georgia,serif">The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.</span></p><p>&nbsp;</p><p><span style="font-family:Georgia,serif">Sincerely</span></p><p><span style="font-family:Georgia,serif">*signature*</span></p><p><span style="font-family:Georgia,serif">_______________</span></p><p><span style="font-family:Georgia,serif">*letter-handler*</span></p><p><span style="font-family:Georgia,serif">*letter-handler-designation*</span></p><p>&nbsp;</p><p><span style="font-family:Georgia,serif">_______________</span></p><p><span style="font-family:Georgia,serif">*employee-name*</span></p><p><span style="font-family:Georgia,serif">*today*</span></p>'
        ],
        [
            'title' => 'Template Four',
            'description' => '<p style="text-align:right">Date: *today*</p><p>Dear *employee-name*</p><p>Congratulations!</p><p>&nbsp;</p><p style="text-align:center">Subject: *subject*</p><p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif">We are really pleased to inform you that with your performance as a *job-title* your monthly salary has been adjusted by a raise of NPR *raise-amount* (in words). You will now be receiving NPR *monthly-salary* effective from *increment-date* per month. All salary related information is to be kept strictly confidential between you and the company.</span></span></p><p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif">This increment in your salary is on the basis of your score in mid-year performance review *year*. </span></span></p><p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif">All other terms and conditions of employment remain unchanged. We are confident you will keep contributing effectively and efficiently to the company.</span></span></p><p style="text-align:justify"><span style="font-size:11pt"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="color:black">On behalf of *letter-handler*</span></span></span></span></p><p style="text-align:justify">&nbsp;</p><p style="text-align:justify">Sincerely,</p><p style="text-align:justify">*signature*</p>'
        ],
        [
            'title' => 'Custom',
            'description' => ''
        ]
    ]
];

?>